# Generated by Django 5.1.5 on 2025-01-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='chat',
            name='response',
            field=models.TextField(),
        ),
    ]
